version: "3"

services: 
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      default: